"""One command that says whether anything broke.

    python scripts/check_regressions.py             # retrieval only, offline
    python scripts/check_regressions.py --live      # + groundedness and cost
    python scripts/check_regressions.py --live --runs 3

Exits non-zero on regression, so it works as a pre-push hook or a CI step.

Questions run concurrently. Sequentially the live suite takes ~2 minutes, which
is long enough that it quietly becomes a nightly job — and a nightly safety net
finds regressions a day late.
"""

from __future__ import annotations

import argparse
import asyncio
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app.core.regression import (  # noqa: E402
    BASELINE_PATH,
    RebaselineRefused,
    RegressionResult,
    check_instrument,
    save_baseline,
)
from app.rag.chunking import chunk_page  # noqa: E402
from app.rag.decomposition import HeuristicDecomposer, multi_query_search  # noqa: E402
from app.rag.embedders import FakeEmbedder  # noqa: E402
from app.rag.evaluation import evaluate_retrieval, load_cases  # noqa: E402
from app.rag.retrieval import HybridRetriever  # noqa: E402
from scripts.seed_content import load_offline_corpus  # noqa: E402

ANSWERABLE = [
    "What is the current release plan?",
    "What work is holding up the release?",
    "Which controls are still outstanding before go-live?",
    "What is the status of the Acme work and are there contractual risks?",
]

UNANSWERABLE = [
    "Who approved the Acme security exception?",
    "What is our parental leave policy?",
    "What was the exact customer revenue generated by Acme last quarter?",
]


def build_retriever():
    chunks = [c for page in load_offline_corpus() for c in chunk_page(page)]
    return HybridRetriever(chunks, FakeEmbedder(), candidate_pool=20)


async def check_retrieval(result: RegressionResult) -> None:
    """Score retrieval with decomposition enabled.

    `evaluate_retrieval` takes a synchronous `search`, and decomposition is
    async. Calling `asyncio.run` inside the adapter fails once this runs under
    an existing loop — so the async work happens up front and the adapter reads
    a precomputed table. Also faster: every query is resolved concurrently.
    """
    retriever = build_retriever()
    decomposer = HeuristicDecomposer()
    cases = load_cases("docs/eval_set.json")

    resolved = await asyncio.gather(
        *(
            multi_query_search(retriever, decomposer, case.question, top_k=5)
            for case in cases
        )
    )
    table = {
        case.question: hits for case, (hits, _) in zip(cases, resolved)
    }

    class Precomputed:
        def search(self, query, top_k=5):
            return table.get(query, [])[:top_k]

    report = evaluate_retrieval(Precomputed(), cases, k=5)
    result.add("recall_at_5", report.recall_at_k)

    by_category = report.by_category()
    for key, category in (
        ("cross_source_recall", "cross_source"),
        ("identifier_recall", "identifier"),
    ):
        if category in by_category:
            result.add(key, by_category[category])


async def answer_and_judge(answerer, judge, retriever, decomposer, question, trace):
    """One question end to end. Returns (declined, groundedness report)."""
    from app.agent.answering import (
        REFUSAL_MARKER,
        SYSTEM_PROMPT,
        Passage,
        build_context,
    )
    from app.agent.judge import judge_answer

    with trace.span("question", "node", question=question[:60]):
        hits, _ = await multi_query_search(retriever, decomposer, question, top_k=5)
        passages = [Passage.from_hit(h) for h in hits]

        response = await answerer.complete(
            system=SYSTEM_PROMPT.format(refusal=REFUSAL_MARKER),
            messages=[
                {
                    "role": "user",
                    "content": f"Context passages:\n\n{build_context(passages)}"
                    f"\n\nQuestion: {question}",
                }
            ],
            max_tokens=1000,
        )
        text = response.text.strip()
        if REFUSAL_MARKER in text:
            return True, None

        return False, await judge_answer(judge, text, passages)


async def check_live(
    result: RegressionResult, runs: int, judge_model: str
) -> None:
    from app.agent.judge import Verdict
    from app.agent.llm import AnthropicLLM
    from app.core.tracing import TracedLLM, Trace

    retriever = build_retriever()
    decomposer = HeuristicDecomposer()

    totals = {v: 0 for v in Verdict}
    declined_when_should = 0
    answered_when_should_decline = 0
    traces: list[Trace] = []

    for _ in range(runs):
        trace = Trace()
        answerer = TracedLLM(AnthropicLLM(), trace, kind="llm")
        judge = TracedLLM(
            AnthropicLLM(model=judge_model), trace, kind="judge"
        )
        traces.append(trace)

        with trace.span("suite", "node"):
            # Questions are independent. Sequentially this is ~2 minutes.
            outcomes = await asyncio.gather(
                *(
                    answer_and_judge(answerer, judge, retriever, decomposer, q, trace)
                    for q in ANSWERABLE + UNANSWERABLE
                )
            )

        for question, (declined, report) in zip(ANSWERABLE + UNANSWERABLE, outcomes):
            is_unanswerable = question in UNANSWERABLE
            if is_unanswerable:
                if declined:
                    declined_when_should += 1
                else:
                    answered_when_should_decline += 1
                continue
            if report:
                for judged in report.judged:
                    totals[judged.verdict] += 1

    claims = sum(totals.values())
    if claims:
        result.add("groundedness_supported", totals[Verdict.SUPPORTED] / claims)
        result.add("groundedness_overreach", totals[Verdict.OVERREACH] / claims)
        result.add("groundedness_unsupported", totals[Verdict.UNSUPPORTED] / claims)

    expected_refusals = len(UNANSWERABLE) * runs
    result.add("refusal_rate", declined_when_should / expected_refusals)

    # Separated, because one number mixed what the client pays per question
    # with what CI pays per commit, and reported the difference as a regression.
    answer_cost = sum(
        s.cost(t.rates) for t in traces for s in t.spans if s.kind == "llm"
    )
    judge_cost = sum(
        s.cost(t.rates) for t in traces for s in t.spans if s.kind == "judge"
    )
    answers = sum(len([s for s in t.spans if s.kind == "llm"]) for t in traces)
    evaluated = len(ANSWERABLE) * runs

    if answers:
        result.add("cost_per_answer", answer_cost / answers)
    if evaluated:
        result.add("cost_per_eval", (answer_cost + judge_cost) / evaluated)

    print(f"\n  {claims} claims judged across {runs} run(s)")
    print(f"  wall time: {sum(t.wall_ms for t in traces) / 1000:.1f}s")


async def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--live", action="store_true")
    parser.add_argument(
        "--runs", type=int, default=1,
        help="Sampled metrics are noisy; 3 gives a baseline near the centre of "
             "the distribution rather than near an edge.",
    )
    parser.add_argument("--judge-model", default=None)
    parser.add_argument(
        "--force",
        action="store_true",
        help="Re-baseline even though checks are failing. Only when the new "
             "value is the intended one.",
    )
    parser.add_argument(
        "--update-baseline",
        metavar="REASON",
        help="Record the observed values as the new baseline. Requires a "
             "reason, which is written into the file — an unexplained "
             "re-baseline is indistinguishable from one that silenced a "
             "failure.",
    )
    args = parser.parse_args()

    result = RegressionResult(runs=args.runs)

    print("=" * 74)
    print("REGRESSION CHECKS")
    print("=" * 74)
    print("\nretrieval (deterministic):")
    await check_retrieval(result)

    if args.live:
        import os

        from dotenv import load_dotenv

        load_dotenv()
        if not os.getenv("ANTHROPIC_API_KEY"):
            print("\n--live needs ANTHROPIC_API_KEY in .env")
            return 1
        from app.agent.llm import DEFAULT_JUDGE_MODEL

        judge_model = args.judge_model or DEFAULT_JUDGE_MODEL
        print(f"\ngroundedness, refusal and cost (sampled, judge={judge_model}):")

        warning = check_instrument(BASELINE_PATH, judge_model, strict=False)
        if warning:
            print(f"\n  INSTRUMENT CHANGED\n  {warning}\n")
        await check_live(result, args.runs, judge_model)
    else:
        print(
            "\n  (groundedness, refusal and cost skipped — pass --live to check them)"
        )

    print("\n" + result.report())

    if args.update_baseline:
        if not args.live:
            # Partial baselines are worse than none: the live metrics would be
            # dropped and the next --live run would silently fall back to
            # defaults for them.
            print(
                "\n  Refusing to re-baseline from an offline run — it would "
                "\n  discard the groundedness, refusal and cost metrics."
                "\n  Re-run with --live --update-baseline \"reason\"."
            )
            return 1
        try:
            save_baseline(
                result.observed,
                reason=args.update_baseline,
                failing=[key for key, _, _ in result.failed],
                force=args.force,
                runs=args.runs,
                judge_model=judge_model if args.live else "",
            )
        except RebaselineRefused as exc:
            print(f"\n  {exc}")
            return 1
        print(
            f"\n  Baseline updated ({len(result.observed)} metrics)."
            f"\n  reason: {args.update_baseline}"
            + ("\n  (forced over failing checks)" if args.force else "")
        )
        return 0

    return 0 if result.ok else 1


if __name__ == "__main__":
    sys.exit(asyncio.run(main()))
